Toppage
katotakumi/mercari49_team_nagoya pull request #3
Opened 2019-04-27 09:41 UTC by silk-k

トップページの実装

2019-04-27 09:45 UTC, yuki-uchida requested changes

2019-04-27 09:45 UTC, yuki-uchida commented on app/assets/stylesheets/tops.scss
> +.header_surch_bar{
BEMにおいてはアンバサンドを活用して省略系で記述しましょう

2019-04-28 04:22 UTC, silk-k commented on app/assets/stylesheets/tops.scss
> +.header_surch_bar{
省略して記述してみました。

2019-04-28 04:27 UTC, hiroki5123 commented
コンフリクトが起きていますので修正してから再度レビュー申請をお願い致します。

2019-04-28 05:18 UTC, merged