トップページ最新
katotakumi/mercari49_team_nagoya pull request #5
Opened 2019-04-28 07:38 UTC by silk-k

2019-04-28 07:40 UTC, silk-k commented
コンフリが起きていた方を解消しましたが、誤ってマスターにマージしてしまったので
再度作り直しました。

2019-04-28 08:39 UTC, yuki-uchida commented
すいません、このプルリクはWHAT/WHYが書かれていないため、何をしたくて変更を加えているのかわかりません。何をしたくて変更を加えているのかわからないので、こちらもどこを見てレビューすればいいのかわからなくなってしまいます

2019-04-28 08:51 UTC, silk-k commented
# WHAT
メルカリトップページ見た目の実装
（マークアップ）

# WHY
サービスに必須の機能のため

2019-04-28 08:51 UTC, silk-k commented
ご指摘ありがとうございます。
このような形でよろしいでしょうか？

2019-04-28 08:53 UTC, yuki-uchida commented
OKです！

2019-04-28 08:55 UTC, yuki-uchida requested changes

2019-04-28 08:55 UTC, yuki-uchida commented on app/assets/stylesheets/tops.scss
> +.list {
基本的にクラス名はBEMに従って命名しましょう。
様々なところで使用されるCSSは、該当箇所でmixinで呼び出す形にしましょう

2019-04-28 08:55 UTC, yuki-uchida commented on app/assets/stylesheets/tops.scss
> +.header_under_bland{
以降上記の指摘と同じです。
BEMに従ってCSSをかくと、ネストされた形で書くことができ、HTMLファイルと似た構造になるため、レイアウト崩れが起きた時にデバッグがしやすくなります

2019-04-29 06:34 UTC, silk-k commented on app/assets/stylesheets/tops.scss
> +.header_under_bland{
色々なサイトを参考にしてBEMにしたがって書いてみましたが、これで良いのでしょうか。
B・・・ブロック　ほとんどブロックな気がしています。
E・・・エレメント　それほどないですよね。
M・・・モデルファイはほとんどない気がしています。

header(ブロック）
header-top（ブロック）
header-top-logo(ブロック）
header-such-bar（ブロック）
header-such-bar__icon(エレメント）
header-under　（ブロック）

こんな認識になってしまいます。
具体的にどういうところがダメで、こうした方がいいというのを参考までに教えていただきたいです。

2019-04-29 06:34 UTC, silk-k commented on app/assets/stylesheets/tops.scss
> +.list {
mixinもひたすら考えましたが、上手に使えませんでした。
私のコードを元に一つ例をあげていただきたいです。

2019-04-29 06:38 UTC, miyagit approved these changes
LGTM です。

2019-04-29 06:42 UTC, merged